package servlets;
import data.UserDAO;
import model.User;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.time.LocalDateTime;

public class RegisterServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
        HttpSession session = req.getSession(false);
        if(session == null || session.getAttribute("user") != null) {
            res.sendRedirect("/index.jsp");
            return;
        }

        req.getRequestDispatcher("/register.jsp").forward(req, res);
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
        RequestDispatcher reqDispatcher = req.getRequestDispatcher("/register.jsp");
        HttpSession session = req.getSession(false);
        if(session != null) {
            session.setAttribute("error", "You are already logged in!");
            res.sendRedirect("/index.jsp");
            return;
        }
        session = req.getSession();

        String username = req.getParameter("username");
        int age;
        try {
            age = Integer.parseInt(req.getParameter("age"));
        } catch (Exception e) {
            req.setAttribute("error", "Invalid age.");
            reqDispatcher.forward(req, res);
            return;
        }
        String password = req.getParameter("password");
        String confirmPassword = req.getParameter("confirmPassword");

        if(!password.equals(confirmPassword)) {
            req.setAttribute("error", "Passwords do not match!");
            reqDispatcher.forward(req, res);
            return;
        }

        String hashedPassword = BCrypt.hashpw(password, BCrypt.gensalt());  // could not import BCrypt in pom.xml

        LocalDateTime now = LocalDateTime.now();
        User user = new User(-1, username, hashedPassword, age, now, true);  // user_id should be something, not -1
        /* I think UserDAO should be changed. because we can't get user_id to search users by that.
         * we can search users by, for example, username
         * User should be changed too and should not receive user_id as an argument,
         * instead it should be generated by Database */

        ServletContext context = getServletContext();
        UserDAO userDAO = (UserDAO) context.getAttribute("userDAO");
        if(userDAO.findUser(user.getUsername()) != null) {
            req.setAttribute("error", "Username is already taken!");
            req.getRequestDispatcher("/register.jsp").forward(req, res);
            return;
        }
        userDAO.saveUser(user);
        session.setAttribute("user", user);
        res.sendRedirect(req.getContextPath() + "/index.jsp");
    }
}